// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szzeihfoczbpmyprnjjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6emVpaGZvY3picG15cHJuampxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDYxNjYsImV4cCI6MjA1NTYyMjE2Nn0.ATS8Gjz3EnHEnx7gMhBPCJ-w1us41zTefY-y_s5OThg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);